// <auto-generated />
using System;
using ERP_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127190751_MakeOtherDetailsNullable")]
    partial class MakeOtherDetailsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP_System.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ActTime")
                        .HasColumnType("time");

                    b.Property<string>("ActivityData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmpName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OpName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ERP_System.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ERP_System.Models.ChartOfAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCode");

                    b.ToTable("ChartOfAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_ChartOfAccount_AccountType", "[AccountType] IN ('Asset', 'Liability', 'Equity', 'Revenue', 'Expense')");

                            t.HasCheckConstraint("CK_ChartOfAccount_Level", "[Level] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_ChartOfAccount_NormalBalance", "[NormalBalance] IN ('Debit', 'Credit')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ERP_System.Models.CompanyPhone", b =>
                {
                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CompId", "Phone");

                    b.ToTable("CompanyPhones");
                });

            modelBuilder.Entity("ERP_System.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OtherDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ERP_System.Models.CustomerItem", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("CustomerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CustomerItems");
                });

            modelBuilder.Entity("ERP_System.Models.CustomerPhone", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId", "Phone");

                    b.ToTable("CustomerPhones");
                });

            modelBuilder.Entity("ERP_System.Models.DelegateMember", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.ToTable("delegate");
                });

            modelBuilder.Entity("ERP_System.Models.EmpImage", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<byte[]>("EmpImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("EmpId");

                    b.ToTable("EmpImages");
                });

            modelBuilder.Entity("ERP_System.Models.EmpPhone", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpId", "Phone");

                    b.ToTable("EmpPhones");
                });

            modelBuilder.Entity("ERP_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_Employee_RoleType", "[RoleType] IN ('delegate', 'emp')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.ExpenseName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseNames");
                });

            modelBuilder.Entity("ERP_System.Models.Inventory", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ERP_System.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ItemId");

                    b.HasIndex("StoreId");

                    b.ToTable("InventoryTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryTransaction_TransactionType", "[TransactionType] IN ('Purchase', 'PurchaseReturn', 'Sales', 'SalesReturn', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.InvoicePurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InvReturnId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[quantity] * [unitPrice]", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvReturnId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemId");

                    b.ToTable("InvoicePurchaseDetails", t =>
                        {
                            t.HasCheckConstraint("CK_InvoicePurchaseDetail_Status", "[Status] IN ('Purchased', 'Returned')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.InvoicePurchaseHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("AssignedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPostpaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[totalAmount] - [discount]", true);

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RefInvId")
                        .HasColumnType("int");

                    b.Property<decimal>("Remain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByEmployeeId");

                    b.HasIndex("RefInvId");

                    b.HasIndex("StoreId");

                    b.HasIndex("SupplierId");

                    b.ToTable("InvoicePurchaseHeaders", t =>
                        {
                            t.HasCheckConstraint("CK_InvoicePurchaseHeader_InvType", "[InvType] IN ('PurchaseCash', 'PurchaseCredit', 'PurchaseReturn')");

                            t.HasCheckConstraint("CK_InvoicePurchaseHeader_OrderStatus", "[OrderStatus] IN ('wait', 'recieved', 'returned', 'returning')");

                            t.HasCheckConstraint("CK_InvoicePurchaseHeader_PayStatus", "[PayStatus] IN ('open', 'closed')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.InvoiceSaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InvReturnId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[quantity] * [unitPrice]", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvReturnId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemId");

                    b.ToTable("InvoiceSaleDetails", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceSaleDetail_Status", "[Status] IN ('Purchased', 'Returned')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.InvoiceSaleHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsPostpaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[totalAmount] - [discount]", true);

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RefInvId")
                        .HasColumnType("int");

                    b.Property<decimal>("Remain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DelegateId");

                    b.HasIndex("RefInvId");

                    b.HasIndex("StoreId");

                    b.ToTable("InvoiceSaleHeaders", t =>
                        {
                            t.HasCheckConstraint("CK_InvoiceSaleHeader_InvType", "[InvType] IN ('SalesCash', 'SalesReturnCash', 'SalesCredit', 'SalesReturnCredit')");

                            t.HasCheckConstraint("CK_InvoiceSaleHeader_OrderStatus", "[OrderStatus] IN ('wait', 'sent', 'returned', 'returning')");

                            t.HasCheckConstraint("CK_InvoiceSaleHeader_PayStatus", "[PayStatus] IN ('open', 'closed')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CompanyMade")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultStore")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool?>("IsActiveBuy")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActiveSale")
                        .HasColumnType("bit");

                    b.Property<int?>("MinQuantitySale")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("PreventDiscount")
                        .HasColumnType("bit");

                    b.Property<bool>("PreventFraction")
                        .HasColumnType("bit");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UnitNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyMade");

                    b.HasIndex("DefaultStore");

                    b.HasIndex("UnitNumber");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ERP_System.Models.ItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("ERP_System.Models.ItemCode", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCodeValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemId", "ItemCodeValue");

                    b.HasIndex("ItemCodeValue")
                        .IsUnique();

                    b.ToTable("ItemCodes");
                });

            modelBuilder.Entity("ERP_System.Models.ItemImage", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ItemImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ItemId");

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("ERP_System.Models.JournalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EntryId");

                    b.ToTable("JournalDetails");
                });

            modelBuilder.Entity("ERP_System.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvPurId")
                        .HasColumnType("int");

                    b.Property<int?>("InvSaleId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("InvPurId");

                    b.HasIndex("InvSaleId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("ERP_System.Models.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Username");

                    b.HasIndex("EmpId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ERP_System.Models.PurchasePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvPurchaseId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceReturnId")
                        .HasColumnType("int");

                    b.Property<bool>("Out")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvPurchaseId");

                    b.HasIndex("InvoiceReturnId");

                    b.ToTable("PurchasePayments", t =>
                        {
                            t.HasCheckConstraint("CK_PurchasePayment_PaymentMethod", "[PaymentMethod] IN ('cash', 'visa', 'vCash', 'insta')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.RevenueName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RevenueNames");
                });

            modelBuilder.Entity("ERP_System.Models.SalePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("In")
                        .HasColumnType("bit");

                    b.Property<int>("InvSaleId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceReturnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvSaleId");

                    b.HasIndex("InvoiceReturnId");

                    b.ToTable("SalePayments", t =>
                        {
                            t.HasCheckConstraint("CK_SalePayment_PaymentMethod", "[PaymentMethod] IN ('cash', 'visa', 'vCash', 'insta')");
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ERP_System.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ERP_System.Models.StoreImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreImages");
                });

            modelBuilder.Entity("ERP_System.Models.StorePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StorePhones");
                });

            modelBuilder.Entity("ERP_System.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ManagerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ERP_System.Models.SupplierPhone", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SupplierId", "Phone");

                    b.ToTable("SupplierPhones");
                });

            modelBuilder.Entity("ERP_System.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ERP_System.Models.ActivityLog", b =>
                {
                    b.HasOne("ERP_System.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("ERP_System.Models.ChartOfAccount", b =>
                {
                    b.HasOne("ERP_System.Models.ChartOfAccount", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ERP_System.Models.CompanyPhone", b =>
                {
                    b.HasOne("ERP_System.Models.Company", "Company")
                        .WithMany("Phones")
                        .HasForeignKey("CompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ERP_System.Models.CustomerItem", b =>
                {
                    b.HasOne("ERP_System.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ERP_System.Models.CustomerPhone", b =>
                {
                    b.HasOne("ERP_System.Models.Customer", "Customer")
                        .WithMany("Phones")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ERP_System.Models.DelegateMember", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP_System.Models.EmpImage", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "Employee")
                        .WithOne("Image")
                        .HasForeignKey("ERP_System.Models.EmpImage", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP_System.Models.EmpPhone", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "Employee")
                        .WithMany("Phones")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP_System.Models.Inventory", b =>
                {
                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ERP_System.Models.InventoryTransaction", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ERP_System.Models.InvoicePurchaseDetail", b =>
                {
                    b.HasOne("ERP_System.Models.InvoicePurchaseHeader", "ReturnedInvoice")
                        .WithMany()
                        .HasForeignKey("InvReturnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.InvoicePurchaseHeader", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Item");

                    b.Navigation("ReturnedInvoice");
                });

            modelBuilder.Entity("ERP_System.Models.InvoicePurchaseHeader", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.InvoicePurchaseHeader", "RefInvoice")
                        .WithMany()
                        .HasForeignKey("RefInvId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.HasOne("ERP_System.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("RefInvoice");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_System.Models.InvoiceSaleDetail", b =>
                {
                    b.HasOne("ERP_System.Models.InvoiceSaleHeader", "InvReturn")
                        .WithMany()
                        .HasForeignKey("InvReturnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.InvoiceSaleHeader", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvReturn");

                    b.Navigation("Invoice");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ERP_System.Models.InvoiceSaleHeader", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.DelegateMember", "Delegate")
                        .WithMany()
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.InvoiceSaleHeader", "RefInvoice")
                        .WithMany()
                        .HasForeignKey("RefInvId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("Customer");

                    b.Navigation("Delegate");

                    b.Navigation("RefInvoice");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ERP_System.Models.Item", b =>
                {
                    b.HasOne("ERP_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyMade");

                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("DefaultStore");

                    b.HasOne("ERP_System.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitNumber");

                    b.Navigation("Company");

                    b.Navigation("Store");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ERP_System.Models.ItemCategory", b =>
                {
                    b.HasOne("ERP_System.Models.Category", "Category")
                        .WithMany("ItemCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ERP_System.Models.ItemCode", b =>
                {
                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany("Codes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ERP_System.Models.ItemImage", b =>
                {
                    b.HasOne("ERP_System.Models.Item", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ERP_System.Models.JournalDetail", b =>
                {
                    b.HasOne("ERP_System.Models.ChartOfAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.JournalEntry", "Entry")
                        .WithMany("Details")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("ERP_System.Models.JournalEntry", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.InvoicePurchaseHeader", "InvoicePurchase")
                        .WithMany()
                        .HasForeignKey("InvPurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_System.Models.InvoiceSaleHeader", "InvoiceSale")
                        .WithMany()
                        .HasForeignKey("InvSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("InvoicePurchase");

                    b.Navigation("InvoiceSale");
                });

            modelBuilder.Entity("ERP_System.Models.Login", b =>
                {
                    b.HasOne("ERP_System.Models.Employee", "Employee")
                        .WithMany("Logins")
                        .HasForeignKey("EmpId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP_System.Models.PurchasePayment", b =>
                {
                    b.HasOne("ERP_System.Models.InvoicePurchaseHeader", "InvoicePurchase")
                        .WithMany()
                        .HasForeignKey("InvPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.InvoicePurchaseHeader", "InvoiceReturn")
                        .WithMany()
                        .HasForeignKey("InvoiceReturnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InvoicePurchase");

                    b.Navigation("InvoiceReturn");
                });

            modelBuilder.Entity("ERP_System.Models.SalePayment", b =>
                {
                    b.HasOne("ERP_System.Models.InvoiceSaleHeader", "InvoiceSale")
                        .WithMany()
                        .HasForeignKey("InvSaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.InvoiceSaleHeader", "InvoiceReturn")
                        .WithMany()
                        .HasForeignKey("InvoiceReturnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InvoiceReturn");

                    b.Navigation("InvoiceSale");
                });

            modelBuilder.Entity("ERP_System.Models.StoreImage", b =>
                {
                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany("Images")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ERP_System.Models.StorePhone", b =>
                {
                    b.HasOne("ERP_System.Models.Store", "Store")
                        .WithMany("Phones")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ERP_System.Models.SupplierPhone", b =>
                {
                    b.HasOne("ERP_System.Models.Supplier", "Supplier")
                        .WithMany("Phones")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_System.Models.Category", b =>
                {
                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("ERP_System.Models.ChartOfAccount", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ERP_System.Models.Company", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("ERP_System.Models.Customer", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("ERP_System.Models.Employee", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Logins");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("ERP_System.Models.Item", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("ERP_System.Models.JournalEntry", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ERP_System.Models.Store", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("ERP_System.Models.Supplier", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
